# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true

# Mod properties
mod_version = 1.0.0
maven_group = com.stalemated.simplytweaks
archives_name = simply_swords_tweaks
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.20.1
yarn_mappings = 1.20.1+build.10

# Dependencies
fabric_loader_version = 0.18.4
fabric_api_version = 0.92.6+1.20.1
forge_version = 1.20.1-47.4.9

simply_swords_fabric_file_id = 8746035
simply_swords_forge_file_id = 8746028
simply_tooltips_fabric_file_id = 8715150
simply_tooltips_forge_file_id = 8715158
simply_skills_file_id = 6282680

architectury_api_version = 9.2.14
fzzy_config_version = 0.7.6+1.20.1

puffish_skills_file_id_fabric_0_19_0 = 8792786
puffish_skills_file_id_fabric_0_18_3 = 8547669
puffish_skills_file_id_fabric_0_17_3 = 7672793
puffish_skills_file_id_forge_0_19_0 = 8792785
puffish_skills_file_id_forge_0_18_3 = 8547668
puffish_skills_file_id_forge_0_17_3 = 7672794

puffish_attributes_file_id_fabric = 7551332
puffish_attributes_file_id_forge = 7551331

spell_engine_version = 0.15.12+1.20.1
spell_power_version = 0.12.0+1.20.1
player_animator_version = 1.0.2-rc1+1.20
cloth_config_version = 11.1.136
tiny_config_version = 2.3.2
trinkets_file_id = 5173501
cardinal_components_api_version=5.2.3

rebalance_file_id = 5731360

s_lib_version = 2.1.0+1.20.1
yacl_version = 3.6.6+1.20.1
modmenu_version = 7.2.2

# Unused
mixin_extras_version=0.5.0-beta.3

lambdynlights_version=4597897
spruceui_version=5.0.0+1.20

kotlinforforge_version=4.11.0
tomlkt_version=0.3.7
eldritch_end_version=5035580
necronomicon_version=5041803
oracle_index_version=8414533
openpac_version=8230796
mythicmetals_version=0.19.9+1.20.1
irons_spells_version=1.20.1-3.16.2
rei_version=12.1.785
emi_version=1.1.22+1.20.1
