architectury {
    common rootProject.enabled_platforms.split(',')
}

loom {
    mixin {
        useLegacyMixinAp = true
        defaultRefmapName = "simply_swords_tweaks-common.refmap.json"
    }
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    // S-Lib common code
    modCompileOnly "com.stalemated.lib:s-lib-common:${rootProject.s_lib_version}"

    // YACL
    modCompileOnly "dev.isxander:yet-another-config-lib:${rootProject.yacl_version}-fabric"

    // Simply Swords
    modCompileOnly "curse.maven:simply-swords-659887:${rootProject.simply_swords_fabric_file_id}"

    // Rebalance
    modCompileOnly "curse.maven:rebalance-940586:${rootProject.rebalance_file_id}"
}
